#update with:   conda env update --file requirements.yml --prune
name: joe_scan
channels:
  - anaconda
#  - conda-forge
dependencies:
  - anaconda::numpy
  - anaconda::matplotlib
  - anaconda::scipy
  - anaconda::scikit-image
  - anaconda::pip
  - pip:
     - nidaqmx
     - superqt
     - pyqtgraph
