#update with:   conda env update --file requirements.yml --prune
name: galvo_control
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scipy
  - scikit-image
  - pip
  - pip:
      nidaqmx
      superqt
